version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  zookeeper:
    image: zookeeper:3.4.13
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
  order:
    image: order
    container_name: order
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      KAFKA_BROKERS: kafka:9092,kafka:29092
      JAEGER_HOST: jaeger
      JAEGER_PORT: 5775
  inventory:
    image: inventory
    container_name: inventory
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      KAFKA_BROKERS: kafka:9092,kafka:29092
      JAEGER_HOST: jaeger
      JAEGER_PORT: 5775
  payment:
    image: payment
    container_name: payment
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      KAFKA_BROKERS: kafka:9092,kafka:29092
      JAEGER_HOST: jaeger
      JAEGER_PORT: 5775